services:
  - type: web
    name: emosync-backend
    runtime: python
    buildCommand: |
      apt-get update && apt-get install -y libgl1
      pip install -r requirements.txt
    startCommand: python app.py
